import { makeStyles } from '@mui/styles';

export default makeStyles(() => ({
	quiz: {
		position: 'absolute',
		left: '50%',
		top: '50%',
		transform: 'translate(-50%, -50%)',
		padding: '10px',
	},
	card: {
		width: '464px',
		height: '519px',
		boxSizing: 'border-box',
		padding: '12px',
	},
	Title: {
		fontFamily: 'Poppins !important',
		fontWeight: '700 !important',
		fontSize: '36px !important',
		lineHeight: '54px !important',
		textTransform: 'uppercase',
		color: '#F2F2F2',
		fontStyle: 'normal',
	},
	question: {
		fontSize: '20px !important',
		lineHeight: '30px !important',
		color: '#2F527B',
		width: '373px !important',
		paddingTop: '50px',
		paddingLeft: '11px',
		textOverflow: 'ellipsis',
		whiteSpace: 'nowrap',
		overflow: 'hidden',
	},
	boyLogo: {
		position: 'absolute',
		width: '162px',
		height: '116px',
		top: '-11px',
		right: '13px',
	},
	btnText: {
		fontSize: '18px !important',
		lineHeight: '27px !important',
		color: '#FFFFFF !important',
		backgroundColor: '#DD5790 !important',
		width: '116px !important',
		height: '56px',
		float: 'right',
		marginTop: '42px !important',
		'&:hover': {
			backgroundColor: '#FFFFFF !important',
			border: '1px solid #DD5790 !important',
			color: '#DD5790 !important',
			fontWeight: '600 !important',
		},
	},
	option: {
		width: '416px',
		height: '62px',
		boxSizing: 'border-box',
		borderRadius: '12px',
		border: '1px solid rgba(96, 102, 208, 0.8) !important',
		padding: '14px',
		margin: '10px',
		color: 'rgba(96, 102, 208, 0.8) !important',
		fontSize: '22px !important',
		textOverflow: 'ellipsis',
		whiteSpace: 'nowrap',
		overflow: 'hidden',
		'&:hover': {
			backgroundColor: '#DD5790',
			color: 'white !important',
			border: 'none !important',
		},
	},
	optionsContainer: {
		paddingTop: '10px',
		height: '300px',
		minHeight: '300px',
		maxHeight: '300px',
	},
	optionTrue: {
		backgroundColor: '#60BF88',
		color: 'white !important',
		border: 'none !important',
	},
	optionSelected: {
		backgroundColor: '#DD5790',
		color: 'white !important',
		border: 'none !important',
	},
	optionFalse: {
		backgroundColor: '#EA8282',
		color: 'white !important',
		border: 'none !important',
	},
	cardResult: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
	},
	resultTitle: {
		marginTop: '30px  !important',
		fontFamily: 'Poppins',
		fontStyle: 'normal !important',
		fontWeight: '700 !important',
		fontSize: '48px !important',
		lineHeight: '72px  !important',
		color: ' #1D355D  !important',
	},
	againBtn: {
		boxSizing: 'border-box',
		width: '209px',
		height: '62px',
		border: ' 2px solid #1D355D !important',
		borderRadius: '12px !important',
		fontWeight: '600  !important',
		fontSize: '18px !important',
		'&:hover': {
			border: ' 2px solid #DD5790!important',
			color: ' #DD5790 !important',
		},
	},
	resultText: {
		fontWeight: '400 !important',
		fontSize: '18px !important',
		marginTop: '1px  !important',
	},
	numResult: {
		color: 'green !important',
		fontWeight: '700 !important',
		fontSize: '21px !important',
	},
	brainLogo: {
		height: '145px !important',
		right: '0px !important',
	},
	intialText: {
		textAlign: 'center',
		fontSize: '32px !important',
		marginTop: ' 123px !important',
	},
	playBtn: {
		marginTop: ' 80px !important',
		'&:hover': {
			border: ' 2px solid #DD5790!important',
			color: ' #DD5790 !important',
		},
	},
}));
